version: '3'

services:

############################ ZIPKIN SERVER #############################
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=${ES_HOST}
      - ES_PASSWORD=${ES_PASSWORD}
      - ES_USERNAME=${ES_USERNAME}
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    networks:
      - zipkin-example

############################ NETCORE API #############################
  serivce-net:
    build:
      context: ServiceNet
      args: 
        ZIPKIN_HOST: ${ZIPKIN_HOST}
        ZIPKIN_PORT: ${ZIPKIN_PORT}
        SERVICEGO_URL: http://service-go:8080
    ports:
      - 5050:80
    networks: 
      - zipkin-example
    restart: always


############################ GOLANG API #############################
  service-go:
    build:
      context: ServiceGo
      args: 
        ZIPKIN_HOST: ${ZIPKIN_HOST}
        ZIPKIN_PORT: ${ZIPKIN_PORT}
    ports:
      - 5051:8080
    networks: 
      - zipkin-example
    restart: always

############################ Spring api #############################
  service-spring:
    build:
      context: ServiceJava
      args: 
        ZIPKIN_HOST: ${ZIPKIN_HOST}
        ZIPKIN_PORT: ${ZIPKIN_PORT}
    ports:
      - 5052:5002
    networks: 
      - zipkin-example
    restart: always

############################ RABBITMQ SERVER ##########################

  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ../data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - zipkin-example

############################ FILEBEAT ##########################

  es-filebeat:
    build:
      context: ./elastic/filebeat
      args:
        ES_VERSION: ${ES_VERSION}
    environment: 
      - ES_CLOUD_ID=${ES_CLOUD_ID}
      - ES_USERNAME=${ES_USERNAME}
      - ES_PASSWORD=${ES_PASSWORD}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
    networks:
      - zipkin-example

############################ LOGSTASH SERVER ##########################

  es-logstash:
    build:
      context: ./elastic/logstash
      args:
        ES_VERSION: ${ES_VERSION}
    environment: 
      - ES_HOST=${ES_HOST}
      - ES_USERNAME=${ES_USERNAME}
      - ES_PASSWORD=${ES_PASSWORD}
    networks:
      - zipkin-example

networks: 
  zipkin-example: