version: '3'

services:

  # Switch storage type to Elasticsearch
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=${ES_HOSTS}
      - ES_PASSWORD=${ES_PASSWORD}
      - ES_USERNAME=${ES_USERNAME}
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    networks:
      - zipkin-example

  # dotnet core api
  serivce-a:
    build:
      context: ServiceA
      args: 
        ZIPKIN_HOST: ${ZIPKIN_HOST}
        ZIPKIN_PORT: ${ZIPKIN_PORT}
    ports:
      - 5050:80
    networks: 
      - zipkin-example
    restart: always


  # golang api
  serivce-b:
    build:
      context: ServiceB
      args: 
        ZIPKIN_HOST: ${ZIPKIN_HOST}
        ZIPKIN_PORT: ${ZIPKIN_PORT}
    ports:
      - 5051:8080
    networks: 
      - zipkin-example
    restart: always
networks: 
  zipkin-example: